### ISSUE TITLE
Volume widget using pulse device

### ISSUE THREAD

**Issue by Ddorda** [Ddorda/awesome#4]
When using Pulse as device on the volume widget, the volume bar acts like volume is 0%.
this is caused by the output, that contains several channels instead of only one (mono).

the command that being executed:
`amixer -D pulse set Master toggle`

and the output:
`Simple mixer control 'Master',0
  Capabilities: pvolume pswitch pswitch-joined
  Playback channels: Front Left - Front Right
  Limits: Playback 0 - 65536
  Mono:
  Front Left: Playback 65536 [100%] [off]
  Front Right: Playback 65536 [100%] [off]
`

instead of:
`Simple mixer control 'Master',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback 0 - 74
  Mono: Playback 74 [100%] [0.00dB] [on]
`
@galabadi

**Comment by galabadi** [comment]
The pulse driver in some cases will return a different volume than running amixer without it, so we'll need to use it in any command and not only for toggle.
